baseurl = "http://shopetan.github.io/"
languageCode = "ja-jp"
title = "Asobeat"
theme = "hugo-artists-theme"

[params]

# You can use Markdown syntax for urls [text](//url.to/source) for
# most longer texts.

# To provide some metadata for search engines feel free to add a few
# information about you and your website.
name = "Asobeat"
description = "It begins a new play."

# Header an navigation
#
# To change the header background the 'hero-bg-jpg' at 'static/img'.
# Do the same with the logo ('logo.svg').
# But keep the original filename!
[params.header]
title = "Asobeat"
shortBio = "It begins a new play."


# About section
#
# Replace the 'avatar.jpg' under 'static/img' with your own image.
[params.about]
title = "What is this?"
bio = "**Asobeat**は新しい”アソビ”をユーザに提供します。あなたは今までに「鬼ごっこ」や「かくれんぼ」、「缶蹴り」をしたことがありますか？その遊びさえ知っていれば大丈夫です。このデバイスは、これを身につけたユーザ同士で心拍情報や位置情報を共有することで、隠れているユーザの位置情報を表示したり、ユーザ同士の距離が近くなるにつれてバイブレーション通知をしてくれます。遊び方は自由自在です。"

# Contact secion
[params.contact]
title = "Contact"

# The following social network icons are available:
# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
[[params.contact.social]]
icon = "twitter"
link = "//twitter.com/ss_shopetan"

[[params.contact.social]]
icon = "github"
link = "//github.com/shopetan/Asobeat"

[params.footer]
copyright = "Copyright: Team Shopetan 2016"